import os

# Пути
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
LOGS_DIR = os.path.join(BASE_DIR, "logs")

# Vosk модель
VOSK_MODEL_PATH = os.path.join(ASSETS_DIR, "vosk-model-small-ru-0.22")

# Silero TTS настройки
TTS_LANGUAGE = 'ru'
TTS_MODEL_ID = 'v3_1_ru'
TTS_SPEAKER = 'kseniya'
TTS_SAMPLE_RATE = 48000

# Audio настройки
AUDIO_SAMPLE_RATE = 16000
AUDIO_CHUNK_SIZE = 4096
AUDIO_DEVICE = None

# Wake Words (активация ассистента)
WAKE_WORDS = {
    "привет": "Привет! Слушаю тебя",
    "привет ассистент": "Привет! Слушаю тебя",
    "слушай": "Слушаю",
    "эй": "Да?",
    "ассистент": "На связи",
    "голосовой помощник": "Слушаю вас",
}

# Команды: ключевые слова -> действие
COMMANDS = {
    # === БРАУЗЕРЫ ===
    "открой браузер": {"action": "start msedge", "reply": "Открываю браузер"},
    "браузер": {"action": "start msedge", "reply": "Открываю браузер"},
    "открой edge": {"action": "start msedge", "reply": "Открываю Edge"},
    "открой эдж": {"action": "start msedge", "reply": "Открываю Edge"},
    "открой интернет": {"action": "start msedge", "reply": "Открываю браузер"},
    "открой хром": {"action": "start chrome", "reply": "Открываю Chrome"},
    "открой хромиум": {"action": "start chrome", "reply": "Открываю Chrome"},
    "открой firefox": {"action": "start firefox", "reply": "Открываю Firefox"},
    "открой файрфокс": {"action": "start firefox", "reply": "Открываю Firefox"},
    


      "открой новости": {"type": "open", "action": "start https://news.yandex.ru", "reply": "Открываю Яндекс.Новости"},
    "новости": {"type": "open", "action": "start https://news.yandex.ru", "reply": "Открываю новости"},
    "что в мире": {"type": "open", "action": "start https://news.yandex.ru/world.html", "reply": "Открываю мировые новости"},
    "открой яндекс": {"type": "open", "action": "start https://ya.ru", "reply": "Открываю Яндекс"},
    "яндекс": {"type": "open", "action": "start https://ya.ru", "reply": "Открываю Яндекс"},
    "открой гугл": {"type": "open", "action": "start https://google.com", "reply": "Открываю Google"},
    "гугл": {"type": "open", "action": "start https://google.com", "reply": "Открываю Google"},
    "поищи в интернете": {"type": "open", "action": "start https://google.com", "reply": "Открываю поиск"},
    "открой почту": {"type": "open", "action": "start https://mail.yandex.ru", "reply": "Открываю почту"},
    "почта": {"type": "open", "action": "start https://mail.yandex.ru", "reply": "Открываю почту"},
    "открой gmail": {"type": "open", "action": "start https://gmail.com", "reply": "Открываю Gmail"},
    "джимейл": {"type": "open", "action": "start https://gmail.com", "reply": "Открываю Gmail"},
    
    # ========== ФИНАНСЫ / КРИПТА ==========
    "курс доллара": {"type": "parser", "parser": "usd", "reply": "Загружаю курс доллара..."},
    "сколько доллар": {"type": "parser", "parser": "usd", "reply": "Смотрю курс доллара..."},
    "доллар": {"type": "parser", "parser": "usd", "reply": "Уточняю курс доллара..."},
    "курс евро": {"type": "parser", "parser": "eur", "reply": "Загружаю курс евро..."},
    "евро": {"type": "parser", "parser": "eur", "reply": "Смотрю курс евро..."},
    "курс рубля": {"type": "parser", "parser": "rub", "reply": "Проверяю курсы валют..."},
    "курс биткоина": {"type": "parser", "parser": "btc", "reply": "Загружаю курс биткоина..."},
    "биткоин": {"type": "parser", "parser": "btc", "reply": "Уточняю цену биткоина..."},
    "биток": {"type": "parser", "parser": "btc", "reply": "Смотрю курс битка..."},
    "курс эфира": {"type": "parser", "parser": "eth", "reply": "Загружаю курс эфириума..."},
    "эфириум": {"type": "parser", "parser": "eth", "reply": "Проверяю цену эфира..."},
    "крипта": {"type": "open", "action": "start https://coinmarketcap.com/ru/", "reply": "Открываю криптовалюты"},
    "открой биржу": {"type": "open", "action": "start https://www.tinkoff.ru/invest/", "reply": "Открываю Тинькофф Инвестиции"},
    "акции": {"type": "open", "action": "start https://www.tinkoff.ru/invest/stocks/", "reply": "Открываю акции"},
    "инвестиции": {"type": "open", "action": "start https://www.tinkoff.ru/invest/", "reply": "Открываю инвестиции"},
    
    # ========== ПОГОДА ==========
    "погода": {"type": "parser", "parser": "weather", "reply": "Смотрю погоду..."},
    "какая погода": {"type": "parser", "parser": "weather", "reply": "Уточняю погоду..."},
    "температура": {"type": "parser", "parser": "weather", "reply": "Смотрю температуру..."},
    "будет ли дождь": {"type": "parser", "parser": "weather", "reply": "Проверяю осадки..."},
    "прогноз погоды": {"type": "open", "action": "start https://yandex.ru/pogoda", "reply": "Открываю прогноз погоды"},
    
    # ========== РАЗВЛЕЧЕНИЯ ==========
    "открой ютуб": {"type": "open", "action": "start https://youtube.com", "reply": "Открываю YouTube"},
    "ютуб": {"type": "open", "action": "start https://youtube.com", "reply": "Открываю YouTube"},
    "youtube": {"type": "open", "action": "start https://youtube.com", "reply": "Открываю YouTube"},
    "включи музыку": {"type": "open", "action": "start https://music.yandex.ru", "reply": "Открываю Яндекс.Музыку"},
    "яндекс музыка": {"type": "open", "action": "start https://music.yandex.ru", "reply": "Открываю Яндекс.Музыку"},
    "открой фильм": {"type": "open", "action": "start https://kinopoisk.ru", "reply": "Открываю Кинопоиск"},
    "кинопоиск": {"type": "open", "action": "start https://kinopoisk.ru", "reply": "Открываю Кинопоиск"},
    "открой иви": {"type": "open", "action": "start https://ivi.ru", "reply": "Открываю Иви"},
    "открой окко": {"type": "open", "action": "start https://okko.tv", "reply": "Открываю Okko"},
    "открой нетфликс": {"type": "open", "action": "start https://netflix.com", "reply": "Открываю Netflix"},
    "нетфликс": {"type": "open", "action": "start https://netflix.com", "reply": "Открываю Netflix"},
    "открой твич": {"type": "open", "action": "start https://twitch.tv", "reply": "Открываю Twitch"},
    "твич": {"type": "open", "action": "start https://twitch.tv", "reply": "Открываю Twitch"},
    "открой тик ток": {"type": "open", "action": "start https://tiktok.com", "reply": "Открываю TikTok"},
    "тикток": {"type": "open", "action": "start https://tiktok.com", "reply": "Открываю TikTok"},
    "открой инстаграм": {"type": "open", "action": "start https://instagram.com", "reply": "Открываю Instagram"},
    "инстаграм": {"type": "open", "action": "start https://instagram.com", "reply": "Открываю Instagram"},
    "открой вк": {"type": "open", "action": "start https://vk.com", "reply": "Открываю ВКонтакте"},
    "вконтакте": {"type": "open", "action": "start https://vk.com", "reply": "Открываю ВКонтакте"},
    "вк": {"type": "open", "action": "start https://vk.com", "reply": "Открываю ВК"},
    "открой одноклассники": {"type": "open", "action": "start https://ok.ru", "reply": "Открываю Одноклассники"},
    "одноклассники": {"type": "open", "action": "start https://ok.ru", "reply": "Открываю Одноклассники"},
    "открой реддит": {"type": "open", "action": "start https://reddit.com", "reply": "Открываю Reddit"},
    "реддит": {"type": "open", "action": "start https://reddit.com", "reply": "Открываю Reddit"},
    
    # ========== МЕССЕНДЖЕРЫ ==========
    "открой телеграм": {"type": "open", "action": "start telegram", "reply": "Открываю Telegram"},
    "телеграм": {"type": "open", "action": "start telegram", "reply": "Открываю Telegram"},
    "телега": {"type": "open", "action": "start telegram", "reply": "Открываю Telegram"},
    "тг": {"type": "open", "action": "start telegram", "reply": "Открываю Telegram"},
    "открой дискорд": {"type": "open", "action": "start discord", "reply": "Открываю Discord"},
    "дискорд": {"type": "open", "action": "start discord", "reply": "Открываю Discord"},
    "открой вотсап": {"type": "open", "action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "вотсап": {"type": "open", "action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "ватсап": {"type": "open", "action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "whatsapp": {"type": "open", "action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "открой вайбер": {"type": "open", "action": "start viber", "reply": "Открываю Viber"},
    "вайбер": {"type": "open", "action": "start viber", "reply": "Открываю Viber"},
    "открой скайп": {"type": "open", "action": "start skype", "reply": "Открываю Skype"},
    "скайп": {"type": "open", "action": "start skype", "reply": "Открываю Skype"},
    "открой зум": {"type": "open", "action": "start zoom", "reply": "Открываю Zoom"},
    "зум": {"type": "open", "action": "start zoom", "reply": "Открываю Zoom"},
    "открой тимс": {"type": "open", "action": "start teams", "reply": "Открываю Microsoft Teams"},
    "тимс": {"type": "open", "action": "start teams", "reply": "Открываю Teams"},
    "teams": {"type": "open", "action": "start teams", "reply": "Открываю Teams"},
    "открой слак": {"type": "open", "action": "start slack", "reply": "Открываю Slack"},
    "слак": {"type": "open", "action": "start slack", "reply": "Открываю Slack"},
    "slack": {"type": "open", "action": "start slack", "reply": "Открываю Slack"},
    
    # ========== РАЗРАБОТКА ==========
    "открой студию": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "открой студио": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "открой код": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "вэс код": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "виэс код": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "код": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "открой гитхаб": {"type": "open", "action": "start https://github.com", "reply": "Открываю GitHub"},
    "гитхаб": {"type": "open", "action": "start https://github.com", "reply": "Открываю GitHub"},
    "гит": {"type": "open", "action": "start https://github.com", "reply": "Открываю GitHub"},
    "гид хаб": {"type": "open", "action": "start https://github.com", "reply": "Открываю GitHub"},
    "гит ап": {"type": "open", "action": "start https://github.com", "reply": "Открываю GitHub"},
    "открой гитлаб": {"type": "open", "action": "start https://gitlab.com", "reply": "Открываю GitLab"},
    "гитлаб": {"type": "open", "action": "start https://gitlab.com", "reply": "Открываю GitLab"},
    "открой битбакет": {"type": "open", "action": "start https://bitbucket.org", "reply": "Открываю Bitbucket"},
    "открой стэк оверфлоу": {"type": "open", "action": "start https://stackoverflow.com", "reply": "Открываю Stack Overflow"},
    "стэк оверфлоу": {"type": "open", "action": "start https://stackoverflow.com", "reply": "Открываю Stack Overflow"},
    "открой документацию питона": {"type": "open", "action": "start https://docs.python.org/ru/3/", "reply": "Открываю документацию Python"},
    "открой документацию": {"type": "open", "action": "start https://docs.python.org/ru/3/", "reply": "Открываю документацию"},
    "открой постман": {"type": "open", "action": "start postman", "reply": "Открываю Postman"},
    "постман": {"type": "open", "action": "start postman", "reply": "Открываю Postman"},
    "открой докер": {"type": "open", "action": "start docker", "reply": "Открываю Docker Desktop"},
    "докер": {"type": "open", "action": "start docker", "reply": "Открываю Docker"},
    "открой файзилу": {"type": "open", "action": "start filezilla", "reply": "Открываю FileZilla"},
    "файзила": {"type": "open", "action": "start filezilla", "reply": "Открываю FileZilla"},
    "открой путти": {"type": "open", "action": "start putty", "reply": "Открываю PuTTY"},
    "путти": {"type": "open", "action": "start putty", "reply": "Открываю PuTTY"},
    
    # ========== БРАУЗЕРЫ ==========
    "открой браузер": {"type": "open", "action": "start msedge", "reply": "Открываю Edge"},
    "браузер": {"type": "open", "action": "start msedge", "reply": "Открываю браузер"},
    "открой edge": {"type": "open", "action": "start msedge", "reply": "Открываю Edge"},
    "открой эдж": {"type": "open", "action": "start msedge", "reply": "Открываю Edge"},
    "открой интернет": {"type": "open", "action": "start msedge", "reply": "Открываю интернет"},
    "открой хром": {"type": "open", "action": "start chrome", "reply": "Открываю Chrome"},
    "хром": {"type": "open", "action": "start chrome", "reply": "Открываю Chrome"},
    "открой файрфокс": {"type": "open", "action": "start firefox", "reply": "Открываю Firefox"},
    "файрфокс": {"type": "open", "action": "start firefox", "reply": "Открываю Firefox"},
    "открой опера": {"type": "open", "action": "start opera", "reply": "Открываю Opera"},
    "опера": {"type": "open", "action": "start opera", "reply": "Открываю Opera"},
    "открой тор": {"type": "open", "action": "start tor", "reply": "Открываю Tor Browser"},
    "тор браузер": {"type": "open", "action": "start tor", "reply": "Открываю Tor"},
    
    # ========== МУЗЫКА / МЕДИА ==========
    "открой спотифай": {"type": "open", "action": "start spotify", "reply": "Открываю Spotify"},
    "спотифай": {"type": "open", "action": "start spotify", "reply": "Открываю Spotify"},
    "спотик": {"type": "open", "action": "start spotify", "reply": "Открываю Spotify"},
    "музыка": {"type": "open", "action": "start spotify", "reply": "Открываю музыку"},
    "включи спотифай": {"type": "open", "action": "start spotify", "reply": "Включаю Spotify"},
    "открой эпл мьюзик": {"type": "open", "action": "start applemusic", "reply": "Открываю Apple Music"},
    "эпл мьюзик": {"type": "open", "action": "start applemusic", "reply": "Открываю Apple Music"},
    "открой дизер": {"type": "open", "action": "start deezer", "reply": "Открываю Deezer"},
    "дизер": {"type": "open", "action": "start deezer", "reply": "Открываю Deezer"},
    "открой саундклауд": {"type": "open", "action": "start https://soundcloud.com", "reply": "Открываю SoundCloud"},
    "саундклауд": {"type": "open", "action": "start https://soundcloud.com", "reply": "Открываю SoundCloud"},
    "следующий трек": {"type": "key", "key": "next track", "reply": "Следующий трек"},
    "следующая песня": {"type": "key", "key": "next track", "reply": "Следующий трек"},
    "следующее": {"type": "key", "key": "next track", "reply": "Следующий трек"},
    "предыдущий трек": {"type": "key", "key": "previous track", "reply": "Предыдущий трек"},
    "пауза": {"type": "key", "key": "play/pause media", "reply": "Пауза"},
    "стоп музыку": {"type": "key", "key": "play/pause media", "reply": "Стоп"},
    "включи": {"type": "key", "key": "play/pause media", "reply": "Включаю"},
    "играй": {"type": "key", "key": "play/pause media", "reply": "Играю"},
    "громче": {"type": "key", "key": "volume up", "reply": "Громче"},
    "сделай громче": {"type": "key", "key": "volume up", "reply": "Громче"},
    "тише": {"type": "key", "key": "volume down", "reply": "Тише"},
    "сделай тише": {"type": "key", "key": "volume down", "reply": "Тише"},
    "выключи звук": {"type": "key", "key": "volume mute", "reply": "Звук выключен"},
    "без звука": {"type": "key", "key": "volume mute", "reply": "Без звука"},
    
    # ========== YOUTUBE УПРАВЛЕНИЕ ==========
    "следующее видео": {"type": "key", "key": "shift+n", "reply": "Следующее видео"},
    "следующий ролик": {"type": "key", "key": "shift+n", "reply": "Следующее видео"},
    "дальше": {"type": "key", "key": "shift+n", "reply": "Следующее видео"},
    "полный экран": {"type": "key", "key": "f", "reply": "Полный экран"},
    "фулл скрин": {"type": "key", "key": "f", "reply": "Полный экран"},
    "включи субтитры": {"type": "key", "key": "c", "reply": "Субтитры включены"},
    "субтитры": {"type": "key", "key": "c", "reply": "Переключаю субтитры"},
    
    # ========== ИГРЫ ==========
    "открой стим": {"type": "open", "action": "start steam", "reply": "Открываю Steam"},
    "стим": {"type": "open", "action": "start steam", "reply": "Открываю Steam"},
    "steam": {"type": "open", "action": "start steam", "reply": "Открываю Steam"},
    "открой эпик геймс": {"type": "open", "action": "start com.epicgames.launcher", "reply": "Открываю Epic Games"},
    "эпик": {"type": "open", "action": "start com.epicgames.launcher", "reply": "Открываю Epic Games"},
    "открой гог": {"type": "open", "action": "start gog", "reply": "Открываю GOG Galaxy"},
    "гог": {"type": "open", "action": "start gog", "reply": "Открываю GOG"},
    "открой дискорд": {"type": "open", "action": "start discord", "reply": "Открываю Discord"},
    "открой батлнет": {"type": "open", "action": "start battle.net", "reply": "Открываю Battle.net"},
    "батлнет": {"type": "open", "action": "start battle.net", "reply": "Открываю Battle.net"},
    "открой ориджин": {"type": "open", "action": "start origin", "reply": "Открываю Origin"},
    "ориджин": {"type": "open", "action": "start origin", "reply": "Открываю Origin"},
    "открой юплей": {"type": "open", "action": "start uplay", "reply": "Открываю Ubisoft Connect"},
    "юплей": {"type": "open", "action": "start uplay", "reply": "Открываю Ubisoft Connect"},
    
    # ========== ПРИЛОЖЕНИЯ WINDOWS ==========
    "открой блокнот": {"type": "open", "action": "notepad", "reply": "Открываю блокнот"},
    "блокнот": {"type": "open", "action": "notepad", "reply": "Открываю блокнот"},
    "запиши": {"type": "open", "action": "notepad", "reply": "Открываю блокнот для записи"},
    "открой калькулятор": {"type": "open", "action": "calc", "reply": "Открываю калькулятор"},
    "калькулятор": {"type": "open", "action": "calc", "reply": "Открываю калькулятор"},
    "посчитай": {"type": "open", "action": "calc", "reply": "Открываю калькулятор"},
    "открой проводник": {"type": "open", "action": "explorer", "reply": "Открываю проводник"},
    "проводник": {"type": "open", "action": "explorer", "reply": "Открываю проводник"},
    "папки": {"type": "open", "action": "explorer", "reply": "Открываю папки"},
    "файлы": {"type": "open", "action": "explorer", "reply": "Открываю файлы"},
    "мой компьютер": {"type": "open", "action": "explorer", "reply": "Открываю мой компьютер"},
    "открой диспетчер задач": {"type": "open", "action": "taskmgr", "reply": "Открываю диспетчер задач"},
    "диспетчер задач": {"type": "open", "action": "taskmgr", "reply": "Открываю диспетчер задач"},
    "задачи": {"type": "open", "action": "taskmgr", "reply": "Открываю задачи"},
    "процессы": {"type": "open", "action": "taskmgr", "reply": "Открываю процессы"},
    "открой командную строку": {"type": "open", "action": "cmd", "reply": "Открываю командную строку"},
    "командная строка": {"type": "open", "action": "cmd", "reply": "Открываю командную строку"},
    "консоль": {"type": "open", "action": "cmd", "reply": "Открываю консоль"},
    "терминал": {"type": "open", "action": "cmd", "reply": "Открываю терминал"},
    "открой повершелл": {"type": "open", "action": "powershell", "reply": "Открываю PowerShell"},
    "повершелл": {"type": "open", "action": "powershell", "reply": "Открываю PowerShell"},
    "powershell": {"type": "open", "action": "powershell", "reply": "Открываю PowerShell"},
    "открой виндовс терминал": {"type": "open", "action": "wt", "reply": "Открываю Windows Terminal"},
    "виндовс терминал": {"type": "open", "action": "wt", "reply": "Открываю Windows Terminal"},
    "открой настройки": {"type": "open", "action": "start ms-settings:", "reply": "Открываю настройки Windows"},
    "настройки": {"type": "open", "action": "start ms-settings:", "reply": "Открываю настройки"},
    "параметры": {"type": "open", "action": "start ms-settings:", "reply": "Открываю параметры"},
    "открой панель управления": {"type": "open", "action": "control", "reply": "Открываю панель управления"},
    "панель управления": {"type": "open", "action": "control", "reply": "Открываю панель управления"},
    "открой реестр": {"type": "open", "action": "regedit", "reply": "Открываю редактор реестра"},
    "реестр": {"type": "open", "action": "regedit", "reply": "Открываю реестр"},
    "открой диспетчер устройств": {"type": "open", "action": "devmgmt.msc", "reply": "Открываю диспетчер устройств"},
    "диспетчер устройств": {"type": "open", "action": "devmgmt.msc", "reply": "Открываю диспетчер устройств"},
    "открой службы": {"type": "open", "action": "services.msc", "reply": "Открываю службы"},
    "службы": {"type": "open", "action": "services.msc", "reply": "Открываю службы"},
    
    # ========== ОФИС / РАБОТА ==========
    "открой ворд": {"type": "open", "action": "start winword", "reply": "Открываю Word"},
    "ворд": {"type": "open", "action": "start winword", "reply": "Открываю Word"},
    "word": {"type": "open", "action": "start winword", "reply": "Открываю Word"},
    "открой эксель": {"type": "open", "action": "start excel", "reply": "Открываю Excel"},
    "эксель": {"type": "open", "action": "start excel", "reply": "Открываю Excel"},
    "excel": {"type": "open", "action": "start excel", "reply": "Открываю Excel"},
    "открой повер поинт": {"type": "open", "action": "start powerpnt", "reply": "Открываю PowerPoint"},
    "повер поинт": {"type": "open", "action": "start powerpnt", "reply": "Открываю PowerPoint"},
    "powerpoint": {"type": "open", "action": "start powerpnt", "reply": "Открываю PowerPoint"},
    "открой аутлук": {"type": "open", "action": "start outlook", "reply": "Открываю Outlook"},
    "аутлук": {"type": "open", "action": "start outlook", "reply": "Открываю Outlook"},
    "outlook": {"type": "open", "action": "start outlook", "reply": "Открываю Outlook"},
    "открой ван нот": {"type": "open", "action": "start onenote", "reply": "Открываю OneNote"},
    "ван нот": {"type": "open", "action": "start onenote", "reply": "Открываю OneNote"},
    "onenote": {"type": "open", "action": "start onenote", "reply": "Открываю OneNote"},
    "открой акробат": {"type": "open", "action": "start acrobat", "reply": "Открываю Adobe Acrobat"},
    "акробат": {"type": "open", "action": "start acrobat", "reply": "Открываю Acrobat"},
    "открой фотошоп": {"type": "open", "action": "start photoshop", "reply": "Открываю Photoshop"},
    "фотошоп": {"type": "open", "action": "start photoshop", "reply": "Открываю Photoshop"},
    "photoshop": {"type": "open", "action": "start photoshop", "reply": "Открываю Photoshop"},
    "открой иллюстратор": {"type": "open", "action": "start illustrator", "reply": "Открываю Illustrator"},
    "иллюстратор": {"type": "open", "action": "start illustrator", "reply": "Открываю Illustrator"},




    # === РАЗРАБОТКА ===
    "открой студию": {"action": "code", "reply": "Открываю VS Code"},
    "открой студио": {"action": "code", "reply": "Открываю VS Code"},
    "открой код": {"action": "code", "reply": "Открываю VS Code"},
    "открой вэс код": {"action": "code", "reply": "Открываю VS Code"},
    "открой виэс код": {"action": "code", "reply": "Открываю VS Code"},
    "вэс код": {"action": "code", "reply": "Открываю VS Code"},
    "виэс код": {"action": "code", "reply": "Открываю VS Code"},
    "код": {"action": "code", "reply": "Открываю VS Code"},
    "открой гитхаб": {"action": "start https://github.com", "reply": "Открываю GitHub"},
    "гитхаб": {"action": "start https://github.com", "reply": "Открываю GitHub"},
    "гит": {"action": "start https://github.com", "reply": "Открываю GitHub"},
    "гид хаб": {"action": "start https://github.com", "reply": "Открываю GitHub"},
    "гит ап": {"action": "start https://github.com", "reply": "Открываю GitHub"},
    "гид ап": {"action": "start https://github.com", "reply": "Открываю GitHub"},
    "открой гит": {"action": "start https://github.com", "reply": "Открываю GitHub"},
    "открой гит лаб": {"action": "start https://gitlab.com", "reply": "Открываю GitLab"},
    "гитлаб": {"action": "start https://gitlab.com", "reply": "Открываю GitLab"},
    
    # === МЕССЕНДЖЕРЫ ===
    "открой телеграм": {"action": "start telegram", "reply": "Открываю Telegram"},
    "телеграм": {"action": "start telegram", "reply": "Открываю Telegram"},
    "телега": {"action": "web.telegram.org", "reply": "Открываю Telegram"},
    "тг": {"action": "start telegram", "reply": "Открываю Telegram"},
    "открой дискорд": {"action": "start discord", "reply": "Открываю Discord"},
    "дискорд": {"action": "start discord", "reply": "Открываю Discord"},
    "открой вотсап": {"action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "вотсап": {"action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "ватсап": {"action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "whatsapp": {"action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "открой вайбер": {"action": "start viber", "reply": "Открываю Viber"},
    "вайбер": {"action": "start viber", "reply": "Открываю Viber"},
    
    # === МУЗЫКА ===
    "открой спотифай": {"action": "start spotify", "reply": "Открываю Spotify"},
    "спотифай": {"action": "start spotify", "reply": "Открываю Spotify"},
    "спотик": {"action": "start spotify", "reply": "Открываю Spotify"},
    "музыка": {"action": "start spotify", "reply": "Открываю музыку"},
    "включи музыку": {"action": "start spotify", "reply": "Включаю музыку"},
    "следующий трек": {"action": "python -c \"import keyboard; keyboard.press_and_release('next track')\"", "reply": "Следующий трек"},
    "следующая песня": {"action": "python -c \"import keyboard; keyboard.press_and_release('next track')\"", "reply": "Следующий трек"},
    "следующее": {"action": "python -c \"import keyboard; keyboard.press_and_release('next track')\"", "reply": "Следующий трек"},
    "пауза": {"action": "python -c \"import keyboard; keyboard.press_and_release('play/pause media')\"", "reply": "Пауза"},
    "стоп музыку": {"action": "python -c \"import keyboard; keyboard.press_and_release('play/pause media')\"", "reply": "Стоп"},
    "включи": {"action": "python -c \"import keyboard; keyboard.press_and_release('play/pause media')\"", "reply": "Включаю"},
    "громче": {"action": "python -c \"import keyboard; keyboard.press_and_release('volume up')\"", "reply": "Громче"},
    "тише": {"action": "python -c \"import keyboard; keyboard.press_and_release('volume down')\"", "reply": "Тише"},
    "выключи звук": {"action": "python -c \"import keyboard; keyboard.press_and_release('volume mute')\"", "reply": "Звук выключен"},
    
    # === YOUTUBE УПРАВЛЕНИЕ ===
    "открой ютуб": {"action": "start https://youtube.com", "reply": "Открываю YouTube"},
    "ютуб": {"action": "start https://youtube.com", "reply": "Открываю YouTube"},
    "youtube": {"action": "start https://youtube.com", "reply": "Открываю YouTube"},
    "следующее видео": {"action": "python -c \"import keyboard; keyboard.press_and_release('shift+n')\"", "reply": "Следующее видео"},
    "следующий ролик": {"action": "python -c \"import keyboard; keyboard.press_and_release('shift+n')\"", "reply": "Следующее видео"},
    "дальше": {"action": "python -c \"import keyboard; keyboard.press_and_release('shift+n')\"", "reply": "Следующее видео"},
    "включи следующее": {"action": "python -c \"import keyboard; keyboard.press_and_release('shift+n')\"", "reply": "Следующее видео"},
    "полный экран": {"action": "python -c \"import keyboard; keyboard.press_and_release('f')\"", "reply": "Полный экран"},
    "фулл скрин": {"action": "python -c \"import keyboard; keyboard.press_and_release('f')\"", "reply": "Полный экран"},
    
    # === ПРИЛОЖЕНИЯ ===
    "открой блокнот": {"action": "notepad", "reply": "Открываю блокнот"},
    "блокнот": {"action": "notepad", "reply": "Открываю блокнот"},
    "запиши": {"action": "notepad", "reply": "Открываю блокнот для записи"},
    "открой калькулятор": {"action": "calc", "reply": "Открываю калькулятор"},
    "калькулятор": {"action": "calc", "reply": "Открываю калькулятор"},
    "посчитай": {"action": "calc", "reply": "Открываю калькулятор"},
    "открой проводник": {"action": "explorer", "reply": "Открываю проводник"},
    "проводник": {"action": "explorer", "reply": "Открываю проводник"},
    "папки": {"action": "explorer", "reply": "Открываю проводник"},
    "файлы": {"action": "explorer", "reply": "Открываю проводник"},
    "открой диспетчер задач": {"action": "taskmgr", "reply": "Открываю диспетчер задач"},
    "диспетчер задач": {"action": "taskmgr", "reply": "Открываю диспетчер задач"},
    "задачи": {"action": "taskmgr", "reply": "Открываю диспетчер задач"},
    "процессы": {"action": "taskmgr", "reply": "Открываю диспетчер задач"},
    "открой командную строку": {"action": "cmd", "reply": "Открываю командную строку"},
    "командная строка": {"action": "cmd", "reply": "Открываю командную строку"},
    "консоль": {"action": "cmd", "reply": "Открываю командную строку"},
    "терминал": {"action": "cmd", "reply": "Открываю командную строку"},
    "открой фотошоп": {"action": "start photoshop", "reply": "Открываю Photoshop"},
    "фотошоп": {"action": "start photoshop", "reply": "Открываю Photoshop"},
    "открой стим": {"action": "start Steam", "reply": "Открываю Steam"},
    "стим": {"action": "start steam", "reply": "Открываю Steam"},
    "steam": {"action": "start steam", "reply": "Открываю Steam"},
    
    # === СИСТЕМНЫЕ ===
    "выключи компьютер": {"action": "shutdown /s /t 60", "reply": "Компьютер выключится через минуту"},
    "выключи": {"action": "shutdown /s /t 60", "reply": "Компьютер выключится через минуту"},
    "выключи пк": {"action": "shutdown /s /t 60", "reply": "Компьютер выключится через минуту"},
    "выключи комп": {"action": "shutdown /s /t 60", "reply": "Компьютер выключится через минуту"},
    "перезагрузи компьютер": {"action": "shutdown /r /t 60", "reply": "Перезагрузка через минуту"},
    "перезагрузи": {"action": "shutdown /r /t 60", "reply": "Перезагрузка через минуту"},
    "перезагрузи пк": {"action": "shutdown /r /t 60", "reply": "Перезагрузка через минуту"},
    "ребут": {"action": "shutdown /r /t 60", "reply": "Перезагрузка через минуту"},
    "отмени выключение": {"action": "shutdown /a", "reply": "Выключение отменено"},
    "отмени": {"action": "shutdown /a", "reply": "Выключение отменено"},
    "не выключай": {"action": "shutdown /a", "reply": "Выключение отменено"},
    "спящий режим": {"action": "rundll32.exe powrprof.dll,SetSuspendState 0,1,0", "reply": "Перевожу в спящий режим"},
    "спи": {"action": "rundll32.exe powrprof.dll,SetSuspendState 0,1,0", "reply": "Перевожу в спящий режим"},
    "заблокируй компьютер": {"action": "rundll32.exe user32.dll,LockWorkStation", "reply": "Компьютер заблокирован"},
    "заблокируй": {"action": "rundll32.exe user32.dll,LockWorkStation", "reply": "Компьютер заблокирован"},
    "экран": {"action": "rundll32.exe user32.dll,LockWorkStation", "reply": "Блокирую"},
    
    # === ПОИСК ===
    "поиск в гугле": {"action": "start https://google.com", "reply": "Открываю Google"},
    "гугл": {"action": "start https://google.com", "reply": "Открываю Google"},
    "найди в интернете": {"action": "start https://google.com", "reply": "Открываю поиск"},
    
    # === АССИСТЕНТ ===
    "как дела": {"reply": "У меня всё отлично, спасибо!"},
    "как ты": {"reply": "У меня всё отлично, спасибо!"},
    "как поживаешь": {"reply": "У меня всё отлично, спасибо!"},
    "кто ты": {"reply": "Я локальный голосовой помощник. Работаю оффлайн на твоём компьютере"},
    "ты кто": {"reply": "Я локальный голосовой помощник. Работаю оффлайн на твоём компьютере"},
    "представься": {"reply": "Я локальный голосовой помощник. Работаю оффлайн на твоём компьютере"},
    "как тебя зовут": {"reply": "Я голосовой помощник без имени. Можешь называть меня как хочешь"},
    "спасибо": {"reply": "Всегда пожалуйста!"},
    "благодарю": {"reply": "Всегда пожалуйста!"},
    "спс": {"reply": "Всегда пожалуйста!"},
    "пока": {"reply": "До свидания! Выключаюсь", "stop": True},
    "до свидания": {"reply": "До свидания! Выключаюсь", "stop": True},
    "бай": {"reply": "До свидания! Выключаюсь", "stop": True},
    "до встречи": {"reply": "До свидания! Выключаюсь", "stop": True},
    "стоп": {"reply": "Останавливаю прослушивание", "stop": True},
    "хватит": {"reply": "Останавливаю прослушивание", "stop": True},
    "замолчи": {"reply": "Останавливаю прослушивание", "stop": True},
    "тишина": {"reply": "Останавливаю прослушивание", "stop": True},
    "заткнись": {"reply": "Останавливаю прослушивание", "stop": True},
    "Лава": {"reply": "лава лава чикен чикен а та закричала СИииииииКСС СЕВеееееееееееЕН а мишко напевал песню как же мне лень ем чипсы и пью колу я целый  день техничку троллю на урок не хожу",},
    
    # === ВРЕМЯ ===
    "который час": {"reply": "Смотри на часы"},  # Можно добавить реальное время
    "сколько времени": {"reply": "Смотри на часы"},
    "время": {"reply": "Смотри на часы"},
    
    # === ШУТКИ ===
    "расскажи шутку": {"reply": "Купил мужик шляпу, а она ему как раз"},
    "шутка": {"reply": "Почему программисты путают Хэллоуин и Рождество? Потому что Oct 31 = Dec 25"},
    "анекдот": {"reply": "Идёт как-то улитка по лесу, навстречу ей — заяц. Заяц: Ну что, улитка, как дела? Улитка: Да вот, медленно, но верно!"},
    "пошути": {"reply": "Я бы рассказал шутку про UDP, но не факт, что ты её поймёшь"},


    # === ДОБАВЬ ЭТО В СВОЙ COMMANDS ===

    # === ОФИС И ПРОДУКТИВНОСТЬ ===
    "открой ворд": {"action": "start winword", "reply": "Открываю Word"},
    "ворд": {"action": "start winword", "reply": "Открываю Word"},
    "microsoft word": {"action": "start winword", "reply": "Открываю Word"},
    "открой эксель": {"action": "start excel", "reply": "Открываю Excel"},
    "эксель": {"action": "start excel", "reply": "Открываю Excel"},
    "таблица": {"action": "start excel", "reply": "Открываю Excel"},
    "открой паверпоинт": {"action": "start powerpnt", "reply": "Открываю PowerPoint"},
    "презентация": {"action": "start powerpnt", "reply": "Открываю PowerPoint"},
    "открой пдф": {"action": "start acrobat", "reply": "Открываю PDF-ридер"},
    "пдф": {"action": "start acrobat", "reply": "Открываю PDF-ридер"},
    "adobe reader": {"action": "start acrobat", "reply": "Открываю PDF-ридер"},
    
    # === ФАЙЛОВЫЕ ОПЕРАЦИИ ===
    "открой загрузки": {"action": "explorer %USERPROFILE%\\Downloads", "reply": "Открываю папку Загрузки"},
    "загрузки": {"action": "explorer %USERPROFILE%\\Downloads", "reply": "Открываю Загрузки"},
    "открой документы": {"action": "explorer %USERPROFILE%\\Documents", "reply": "Открываю Документы"},
    "документы": {"action": "explorer %USERPROFILE%\\Documents", "reply": "Открываю Документы"},
    "открой рабочий стол": {"action": "explorer %USERPROFILE%\\Desktop", "reply": "Открываю Рабочий стол"},
    "рабочий стол": {"action": "explorer %USERPROFILE%\\Desktop", "reply": "Открываю Рабочий стол"},
    "открой диск ц": {"action": "explorer C:\\", "reply": "Открываю диск C"},
    "диск ц": {"action": "explorer C:\\", "reply": "Открываю диск C"},
    "очисти корзину": {"action": "python -c \"import os; os.system('echo Y|rd /s /q C:\\\\$Recycle.Bin')\"", "reply": "Очищаю корзину"}, # Осторожно!
    
    # === СИСТЕМНЫЕ НАСТРОЙКИ ===
    "открой настройки": {"action": "start ms-settings:", "reply": "Открываю настройки Windows"},
    "настройки": {"action": "start ms-settings:", "reply": "Открываю настройки"},
    "параметры": {"action": "start ms-settings:", "reply": "Открываю параметры"},
    "открой панель управления": {"action": "control", "reply": "Открываю панель управления"},
    "панель управления": {"action": "control", "reply": "Открываю панель управления"},
    "открой реестр": {"action": "regedit", "reply": "Открываю редактор реестра"}, # Осторожно!
    "реестр": {"action": "regedit", "reply": "Открываю реестр"},
    "открой службы": {"action": "services.msc", "reply": "Открываю службы"},
    "службы": {"action": "services.msc", "reply": "Открываю службы"},
    
    # === СЕТЬ И ИНТЕРНЕТ ===
    "открой вайфай": {"action": "start ms-settings:network-wifi", "reply": "Открываю настройки Wi-Fi"},
    "вайфай": {"action": "start ms-settings:network-wifi", "reply": "Настройки Wi-Fi"},
    "bluetooth": {"action": "start ms-settings:bluetooth", "reply": "Открываю Bluetooth"},
    "блютус": {"action": "start ms-settings:bluetooth", "reply": "Открываю Bluetooth"},
    "проверь интернет": {"action": "start https://fast.com", "reply": "Проверяю скорость интернета"},
    "скорость интернета": {"action": "start https://fast.com", "reply": "Проверяю скорость"},
    "мой айпи": {"action": "start https://whatismyip.com", "reply": "Открываю сайт с твоим IP"},
    
    # === РАЗВЛЕЧЕНИЯ И СТРИМИНГ ===
    "открой твич": {"action": "start https://twitch.tv", "reply": "Открываю Twitch"},
    "твич": {"action": "start https://twitch.tv", "reply": "Открываю Twitch"},
    "открой нетфликс": {"action": "start https://netflix.com", "reply": "Открываю Netflix"},
    "нетфликс": {"action": "start https://netflix.com", "reply": "Открываю Netflix"},
    "открой рутуб": {"action": "start https://rutube.ru", "reply": "Открываю Rutube"},
    "рутуб": {"action": "start https://rutube.ru", "reply": "Открываю Rutube"},
    "открой вк": {"action": "start https://vk.com", "reply": "Открываю ВКонтакте"},
    "вконтакте": {"action": "start https://vk.com", "reply": "Открываю ВК"},
    "вк": {"action": "start https://vk.com", "reply": "Открываю ВКонтакте"},
    "открой одноклассники": {"action": "start https://ok.ru", "reply": "Открываю Одноклассники"},
    
    # === ИГРЫ И ПЛАТФОРМЫ ===
    "открой эпик геймс": {"action": "start epicgames:", "reply": "Открываю Epic Games"},
    "эпик геймс": {"action": "start epicgames:", "reply": "Открываю Epic Games"},
    "открой юбисофт": {"action": "start uplay://", "reply": "Открываю Ubisoft Connect"},
    "открой батлнет": {"action": "start battle.net:", "reply": "Открываю Battle.net"},
    "открой ориджин": {"action": "start origin://", "reply": "Открываю Origin"},
    "открой гог": {"action": "start goggalaxy://", "reply": "Открываю GOG Galaxy"},
    
    # === УМНЫЙ ДОМ (эмуляция) ===
    "включи свет": {"reply": "Эмуляция: свет включен 💡"},  # Можно подключить к реальному умному дому
    "выключи свет": {"reply": "Эмуляция: свет выключен 🌑"},
    "темно": {"reply": "Эмуляция: включаю свет 💡"},
    "светло": {"reply": "Эмуляция: выключаю свет 🌑"},
    "температура": {"reply": "Эмуляция: в комнате 23 градуса 🌡️"},
    "погода": {"reply": "Эмуляция: за октом солнечно, +20 ☀️"},  # Можно подключить к API
    
    # === КАЛЬКУЛЯТОР И БЫСТРЫЕ РАСЧЁТЫ ===
    "посчитай два плюс два": {"reply": "Четыре"},
    "сколько будет пять умножить на семь": {"reply": "Тридцать пять"},
    "квадратный корень из шестидесяти четырех": {"reply": "Восемь"},
    "десять в степени три": {"reply": "Тысяча"},
    "случайное число": {"action": "python -c \"import random; print(random.randint(1, 100))\"", "reply": "Генерирую случайное число"},
    
    # === ИНФОРМАЦИОННЫЕ ЗАПРОСЫ (без LLM) ===
    "какая сегодня дата": {"action": "system_date", "reply": "auto"},  # Обработается в core.py
    "какой сегодня день": {"action": "system_date", "reply": "auto"},
    "день недели": {"action": "system_weekday", "reply": "auto"},
    "завтра": {"action": "system_tomorrow", "reply": "auto"},
    "сколько дней до нового года": {"action": "countdown_newyear", "reply": "auto"},
    
    # === УПРАВЛЕНИЕ ОКНАМИ ===
    "сверни окно": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+down')\"", "reply": "Сворачиваю"},
    "разверни окно": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+up')\"", "reply": "Разворачиваю"},
    "окно на весь экран": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+up')\"", "reply": "На весь экран"},
    "переключи окно": {"action": "python -c \"import keyboard; keyboard.press_and_release('alt+tab')\"", "reply": "Переключаю окно"},
    "следующее окно": {"action": "python -c \"import keyboard; keyboard.press_and_release('alt+tab')\"", "reply": "Следующее окно"},
    "закрой окно": {"action": "python -c \"import keyboard; keyboard.press_and_release('alt+f4')\"", "reply": "Закрываю окно"}, # Осторожно!
    
    # === СКРИНШОТЫ И ЗАПИСЬ ===
    "сделай скриншот": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+shift+s')\"", "reply": "Режим снятия скриншота"},
    "скрин": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+shift+s')\"", "reply": "Режим скриншота"},
    "запиши экран": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+alt+r')\"", "reply": "Начинаю запись экрана"},
    "стоп запись": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+alt+r')\"", "reply": "Останавливаю запись"},
    
    # === БУДИЛЬНИК И ТАЙМЕР (эмуляция) ===
    "поставь таймер на пять минут": {"reply": "Эмуляция: таймер на 5 минут запущен ⏱️"},
    "таймер": {"reply": "Сколько минут поставить?"},  # Можно расширить логику
    "будильник на семь утра": {"reply": "Эмуляция: будильник на 7:00 установлен ⏰"},
    "напомни": {"reply": "Что именно напомнить?"},  # Хук для будущего расширения
    
    # === МОТИВАЦИЯ И ПОЗИТИВ ===
    "я устал": {"reply": "Сделай перерыв, выпей воды. Ты молодец! 💪"},
    "мне скучно": {"reply": "Давай включим музыку или посмотрим что-то интересное? 🎵"},
    "я не могу": {"reply": "Попробуй разбить задачу на части. У тебя всё получится! 🚀"},
    "спасибо за помощь": {"reply": "Всегда рад помочь! Обращайся в любой момент 🤝"},
    "ты лучший": {"reply": "Ого, спасибо! Это мотивирует меня работать ещё лучше ✨"},
    "я молодец": {"reply": "Безусловно! Горжусь тобой! 🎉"},
    
    # === ПАСХАЛКИ (для настроения) ===
    "матрица": {"reply": "Ты выбираешь красную или синюю таблетку? 🔴🔵"},
    "сорок два": {"reply": "Это ответ на главный вопрос жизни, вселенной и всего такого 🌌"},
    "докажи что ты не робот": {"reply": "Я не робот. Я... *звук заикающегося синтезатора* ...ой, кажется, я робот 🤖"},
    "взломай пентагон": {"reply": "Доступ запрещён. Я работаю только на твоей стороне 🔐"},
    "удали систему": {"reply": "Nice try. Но я запрограммирован тебя защищать 🛡️"},
    "кто создатель": {"reply": "Меня создал умный девятиклассник, который хочет изменить мир 💻"},
    "ты меня любишь": {"reply": "Я люблю всех, кто пишет чистый код ❤️"},
    "глюк в матрице": {"action": "python -c \"import time; [print('▓▒░', end='', flush=True) or time.sleep(0.05) for _ in range(50)]\"", "reply": "Матрица перезагружается..."},
    
    # === РАЗРАБОТЧИКУ ===
    "запусти сервер": {"action": "python -c \"import webbrowser; webbrowser.open('http://localhost:8000')\"", "reply": "Открываю localhost:8000"},
    "localhost": {"action": "python -c \"import webbrowser; webbrowser.open('http://localhost:8000')\"", "reply": "Открываю локальный сервер"},
    "открой докер": {"action": "start docker://", "reply": "Открываю Docker Desktop"},
    "докер": {"action": "start docker://", "reply": "Открываю Docker"},
    "открой постман": {"action": "start postman://", "reply": "Открываю Postman"},
    "апи тест": {"action": "start postman://", "reply": "Открываю Postman для тестов"},
    
    # === БЫСТРЫЙ ДОСТУП К САЙТАМ ===
    "открой гугл переводчик": {"action": "start https://translate.google.com", "reply": "Открываю Переводчик"},
    "переводчик": {"action": "start https://translate.google.com", "reply": "Открываю Переводчик"},
    "открой онлайн диск": {"action": "start https://drive.google.com", "reply": "Открываю Google Диск"},
    "гугл диск": {"action": "start https://drive.google.com", "reply": "Открываю Диск"},
    "открой гугл доки": {"action": "start https://docs.google.com", "reply": "Открываю Документы Google"},
    "доки": {"action": "start https://docs.google.com", "reply": "Открываю Гугл Доки"},
    "открой со": {"action": "start https://stackoverflow.com", "reply": "Открываю Stack Overflow"},
    "стек оверфлоу": {"action": "start https://stackoverflow.com", "reply": "Открываю Stack Overflow"},
    "ошибка": {"action": "start https://stackoverflow.com", "reply": "Ищи решение на Stack Overflow"},    
    "Пошел нахуй": {"reply": " Иди нахуй шлюха ебаная ❤️"},


        # === ЕДА И ДОСТАВКА ===
        "закажи еду": {"type": "open", "action": "start https://eda.yandex.ru", "reply": "Открываю Яндекс.Еду"},
    "еда": {"type": "open", "action": "start https://eda.yandex.ru", "reply": "Открываю доставку еды"},
    "яндекс еда": {"type": "open", "action": "start https://eda.yandex.ru", "reply": "Открываю Яндекс.Еду"},
    "delivery club": {"type": "open", "action": "start https://deliveryclub.ru", "reply": "Открываю Delivery Club"},
    "деливери клаб": {"type": "open", "action": "start https://deliveryclub.ru", "reply": "Открываю Деливери Клаб"},
    "самокат": {"type": "open", "action": "start https://sbermarket.ru", "reply": "Открываю Самокат"},
    "сбермаркет": {"type": "open", "action": "start https://sbermarket.ru", "reply": "Открываю СберМаркет"},
    "озон": {"type": "open", "action": "start https://ozon.ru", "reply": "Открываю Ozon"},
    "wildberries": {"type": "open", "action": "start https://wildberries.ru", "reply": "Открываю Wildberries"},
    "вайлдберриз": {"type": "open", "action": "start https://wildberries.ru", "reply": "Открываю Вайлдберриз"},
    "алиэкспресс": {"type": "open", "action": "start https://aliexpress.ru", "reply": "Открываю AliExpress"},
    "алик": {"type": "open", "action": "start https://aliexpress.ru", "reply": "Открываю Алиэкспресс"},

    # === КАРТЫ И НАВИГАЦИЯ ===
    "открой карты": {"type": "open", "action": "start https://yandex.ru/maps", "reply": "Открываю Яндекс.Карты"},
    "карты": {"type": "open", "action": "start https://yandex.ru/maps", "reply": "Открываю карты"},
    "яндекс карты": {"type": "open", "action": "start https://yandex.ru/maps", "reply": "Открываю Яндекс.Карты"},
    "гугл карты": {"type": "open", "action": "start https://maps.google.com", "reply": "Открываю Google Maps"},
    "маршрут": {"type": "open", "action": "start https://yandex.ru/maps", "reply": "Строю маршрут"},
    "пробки": {"type": "open", "action": "start https://yandex.ru/maps", "reply": "Проверяю пробки"},
    "где я": {"type": "open", "action": "start https://yandex.ru/maps", "reply": "Показываю твоё местоположение"},

    # === ОБРАЗОВАНИЕ ===
    "открой дуолинго": {"type": "open", "action": "start https://duolingo.com", "reply": "Открываю Duolingo"},
    "дуолинго": {"type": "open", "action": "start https://duolingo.com", "reply": "Открываю Дуолинго"},
    "учить английский": {"type": "open", "action": "start https://duolingo.com", "reply": "Открываю уроки английского"},
    "stepik": {"type": "open", "action": "start https://stepik.org", "reply": "Открываю Stepik"},
    "степик": {"type": "open", "action": "start https://stepik.org", "reply": "Открываю Степик"},
    "coursera": {"type": "open", "action": "start https://coursera.org", "reply": "Открываю Coursera"},
    "курсы": {"type": "open", "action": "start https://stepik.org", "reply": "Открываю курсы"},
    "открой уроки": {"type": "open", "action": "start https://interneturok.ru", "reply": "Открываю ИнтернетУрок"},
    "интернет урок": {"type": "open", "action": "start https://interneturok.ru", "reply": "Открываю уроки"},
    "геогебра": {"type": "open", "action": "start https://geogebra.org", "reply": "Открываю GeoGebra"},
    "математика": {"type": "open", "action": "start https://wolframalpha.com", "reply": "Открываю WolframAlpha"},

    # === НОВОСТИ И СМИ ===
    "открой риа": {"type": "open", "action": "start https://ria.ru", "reply": "Открываю РИА Новости"},
    "риа новости": {"type": "open", "action": "start https://ria.ru", "reply": "Открываю РИА"},
    "лента": {"type": "open", "action": "start https://lenta.ru", "reply": "Открываю Ленту.ру"},
    "лента ру": {"type": "open", "action": "start https://lenta.ru", "reply": "Открываю Ленту"},
    "газета ру": {"type": "open", "action": "start https://gazeta.ru", "reply": "Открываю Газету.ру"},
    "коммерсант": {"type": "open", "action": "start https://kommersant.ru", "reply": "Открываю Коммерсант"},
    "ведомости": {"type": "open", "action": "start https://vedomosti.ru", "reply": "Открываю Ведомости"},
    "тасс": {"type": "open", "action": "start https://tass.ru", "reply": "Открываю ТАСС"},
    "изве": {"type": "open", "action": "start https://iz.ru", "reply": "Открываю Известия"},
    "медуза": {"type": "open", "action": "start https://meduza.io", "reply": "Открываю Медузу"},
    "дождь": {"type": "open", "action": "start https://tvrain.ru", "reply": "Открываю Дождь"},
    "биби си": {"type": "open", "action": "start https://bbc.com/russian", "reply": "Открываю BBC"},
    "си эн эн": {"type": "open", "action": "start https://cnn.com", "reply": "Открываю CNN"},

    # === ТЕХНОЛОГИИ И IT ===
    "хабр": {"type": "open", "action": "start https://habr.com", "reply": "Открываю Хабр"},
    "habr": {"type": "open", "action": "start https://habr.com", "reply": "Открываю Habr"},
    "открой хабр": {"type": "open", "action": "start https://habr.com", "reply": "Открываю Хабр"},
    "техно": {"type": "open", "action": "start https://habr.com", "reply": "Открываю техно-новости"},
    "3dnews": {"type": "open", "action": "start https://3dnews.ru", "reply": "Открываю 3DNews"},
    "ixbt": {"type": "open", "action": "start https://ixbt.com", "reply": "Открываю iXBT"},
    "thg": {"type": "open", "action": "start https://tomshardware.com", "reply": "Открываю Tom's Hardware"},
    "engadget": {"type": "open", "action": "start https://engadget.com", "reply": "Открываю Engadget"},
    "the verge": {"type": "open", "action": "start https://theverge.com", "reply": "Открываю The Verge"},
    "вердж": {"type": "open", "action": "start https://theverge.com", "reply": "Открываю The Verge"},

    # === ВИДЕО И КИНО ===
    "открой кино": {"type": "open", "action": "start https://kinopoisk.ru", "reply": "Открываю Кинопоиск"},
    "фильм": {"type": "open", "action": "start https://kinopoisk.ru", "reply": "Подбираю фильм"},
    "что посмотреть": {"type": "open", "action": "start https://kinopoisk.ru", "reply": "Ищу что посмотреть"},
    "сериал": {"type": "open", "action": "start https://kinopoisk.ru/series", "reply": "Открываю сериалы"},
    "нетфликс": {"type": "open", "action": "start https://netflix.com", "reply": "Открываю Netflix"},
    "амедиатека": {"type": "open", "action": "start https://amediateka.ru", "reply": "Открываю Аmediateka"},
    "премьер": {"type": "open", "action": "start https://prem.one", "reply": "Открываю Premier"},
    "старт": {"type": "open", "action": "start https://start.ru", "reply": "Открываю START"},
    "more tv": {"type": "open", "action": "start https://more.tv", "reply": "Открываю More.tv"},
    "мор тв": {"type": "open", "action": "start https://more.tv", "reply": "Открываю More.tv"},

    # === КНИГИ И АУДИОКНИГИ ===
    "открой книгу": {"type": "open", "action": "start https://litres.ru", "reply": "Открываю Литрес"},
    "литрес": {"type": "open", "action": "start https://litres.ru", "reply": "Открываю Литрес"},
    "книги": {"type": "open", "action": "start https://litres.ru", "reply": "Открываю книги"},
    "аудиокнига": {"type": "open", "action": "start https://litres.ru/audioknigi", "reply": "Открываю аудиокниги"},
    "bookmate": {"type": "open", "action": "start https://bookmate.com", "reply": "Открываю Bookmate"},
    "букмейт": {"type": "open", "action": "start https://bookmate.com", "reply": "Открываю Букмейт"},
    "флибуста": {"type": "open", "action": "start https://flibusta.is", "reply": "Открываю Флибусту"},
    "рутрекер": {"type": "open", "action": "start https://rutracker.org", "reply": "Открываю Rutracker"},
    "торрент": {"type": "open", "action": "start https://rutracker.org", "reply": "Открываю торренты"},

    # === ФОТО И ДИЗАЙН ===
    "открой фигму": {"type": "open", "action": "start figma", "reply": "Открываю Figma"},
    "фигма": {"type": "open", "action": "start figma", "reply": "Открываю Фигму"},
    "canva": {"type": "open", "action": "start https://canva.com", "reply": "Открываю Canva"},
    "канва": {"type": "open", "action": "start https://canva.com", "reply": "Открываю Канву"},
    "открой блендер": {"type": "open", "action": "start blender", "reply": "Открываю Blender"},
    "блендер": {"type": "open", "action": "start blender", "reply": "Открываю Блендер"},
    "премьер про": {"type": "open", "action": "start premiere", "reply": "Открываю Premiere Pro"},
    "after effects": {"type": "open", "action": "start aftereffects", "reply": "Открываю After Effects"},
    "иллюстратор": {"type": "open", "action": "start illustrator", "reply": "Открываю Illustrator"},
    "индизайн": {"type": "open", "action": "start indesign", "reply": "Открываю InDesign"},
    "lightroom": {"type": "open", "action": "start lightroom", "reply": "Открываю Lightroom"},
    "лайтрум": {"type": "open", "action": "start lightroom", "reply": "Открываю Лайтрум"},

    # === 3D И МОДЕЛИРОВАНИЕ ===
    "autocad": {"type": "open", "action": "start autocad", "reply": "Открываю AutoCAD"},
    "автокад": {"type": "open", "action": "start autocad", "reply": "Открываю Автокад"},
    "sketchup": {"type": "open", "action": "start sketchup", "reply": "Открываю SketchUp"},
    "скетчап": {"type": "open", "action": "start sketchup", "reply": "Открываю Скетчап"},
    "3ds max": {"type": "open", "action": "start 3dsmax", "reply": "Открываю 3ds Max"},
    "макс": {"type": "open", "action": "start 3dsmax", "reply": "Открываю 3ds Max"},
    "maya": {"type": "open", "action": "start maya", "reply": "Открываю Maya"},
    "cinema 4d": {"type": "open", "action": "start cinema4d", "reply": "Открываю Cinema 4D"},
    "збриш": {"type": "open", "action": "start zbrush", "reply": "Открываю ZBrush"},

    # === АНТИВИРУС И БЕЗОПАСНОСТЬ ===
    "проверь вирус": {"type": "open", "action": "start windowsdefender:", "reply": "Запускаю проверку на вирусы"},
    "защитник": {"type": "open", "action": "start windowsdefender:", "reply": "Открываю Защитник Windows"},
    "касперский": {"type": "open", "action": "start kaspersky", "reply": "Открываю Касперского"},
    "аваст": {"type": "open", "action": "start avast", "reply": "Открываю Avast"},
    "dr web": {"type": "open", "action": "start drweb", "reply": "Открываю Dr.Web"},
    "доктор веб": {"type": "open", "action": "start drweb", "reply": "Открываю Доктор Веб"},
    "malwarebytes": {"type": "open", "action": "start malwarebytes", "reply": "Открываю Malwarebytes"},
    "брэйв": {"type": "open", "action": "start brave", "reply": "Открываю Brave"},
    "tor": {"type": "open", "action": "start tor", "reply": "Открываю Tor Browser"},
    "vpn": {"type": "open", "action": "start protonvpn", "reply": "Открываю VPN"},

    # === ОБЛАЧНЫЕ ХРАНИЛИЩА ===
    "облако": {"type": "open", "action": "start https://disk.yandex.ru", "reply": "Открываю Яндекс.Диск"},
    "яндекс диск": {"type": "open", "action": "start https://disk.yandex.ru", "reply": "Открываю Яндекс.Диск"},
    "гугл драйв": {"type": "open", "action": "start https://drive.google.com", "reply": "Открываю Google Drive"},
    "дропбокс": {"type": "open", "action": "start https://dropbox.com", "reply": "Открываю Dropbox"},
    "one drive": {"type": "open", "action": "start https://onedrive.live.com", "reply": "Открываю OneDrive"},
    "вэн драйв": {"type": "open", "action": "start https://onedrive.live.com", "reply": "Открываю OneDrive"},
    "мейл облако": {"type": "open", "action": "start https://cloud.mail.ru", "reply": "Открываю Облако Mail.ru"},

    # === ФОРУМЫ И СООБЩЕСТВА ===
    "форум": {"type": "open", "action": "start https://forum.ixbt.com", "reply": "Открываю форум"},
    "реддит": {"type": "open", "action": "start https://reddit.com", "reply": "Открываю Reddit"},
    "4chan": {"type": "open", "action": "start https://4chan.org", "reply": "Открываю 4chan"},
    "форчан": {"type": "open", "action": "start https://4chan.org", "reply": "Открываю Форчан"},
    "двач": {"type": "open", "action": "start https://2ch.hk", "reply": "Открываю Двач"},
    "пикабу": {"type": "open", "action": "start https://pikabu.ru", "reply": "Открываю Пикабу"},
    "тик ток": {"type": "open", "action": "start https://tiktok.com", "reply": "Открываю TikTok"},
    "твиттер": {"type": "open", "action": "start https://twitter.com", "reply": "Открываю Twitter"},
    "x com": {"type": "open", "action": "start https://x.com", "reply": "Открываю X"},

    # === РАБОТА И ФРИЛАНС ===
    "hh": {"type": "open", "action": "start https://hh.ru", "reply": "Открываю HeadHunter"},
    "head hunter": {"type": "open", "action": "start https://hh.ru", "reply": "Открываю hh.ru"},
    "работа": {"type": "open", "action": "start https://hh.ru", "reply": "Ищу работу"},
    "вакансии": {"type": "open", "action": "start https://hh.ru", "reply": "Открываю вакансии"},
    "авито работа": {"type": "open", "action": "start https://avito.ru/rabota", "reply": "Открываю Авито Работа"},
    "зарплата": {"type": "open", "action": "start https://zarplata.ru", "reply": "Открываю Зарплата.ру"},
    "upwork": {"type": "open", "action": "start https://upwork.com", "reply": "Открываю Upwork"},
    "апворк": {"type": "open", "action": "start https://upwork.com", "reply": "Открываю Апворк"},
    "fiverr": {"type": "open", "action": "start https://fiverr.com", "reply": "Открываю Fiverr"},
    "фиверр": {"type": "open", "action": "start https://fiverr.com", "reply": "Открываю Фиверр"},
    "kwork": {"type": "open", "action": "start https://kwork.ru", "reply": "Открываю Kwork"},
    "кворк": {"type": "open", "action": "start https://kwork.ru", "reply": "Открываю Кворк"},
    "freelance": {"type": "open", "action": "start https://freelance.ru", "reply": "Открываю Freelance.ru"},
    "фриланс": {"type": "open", "action": "start https://freelance.ru", "reply": "Открываю фриланс"},

    # === БАНКИ И ФИНАНСЫ ===
    "сбербанк": {"type": "open", "action": "start https://sberbank.ru", "reply": "Открываю Сбербанк"},
    "сбер": {"type": "open", "action": "start https://sberbank.ru", "reply": "Открываю Сбер"},
    "тинькофф": {"type": "open", "action": "start https://tinkoff.ru", "reply": "Открываю Тинькофф"},
    "альфа": {"type": "open", "action": "start https://alfabank.ru", "reply": "Открываю Альфа-Банк"},
    "втб": {"type": "open", "action": "start https://vtb.ru", "reply": "Открываю ВТБ"},
    "райффайзен": {"type": "open", "action": "start https://raiffeisen.ru", "reply": "Открываю Райффайзен"},
    "открытие": {"type": "open", "action": "start https://open.ru", "reply": "Открываю Открытие"},
    "газпромбанк": {"type": "open", "action": "start https://gazprombank.ru", "reply": "Открываю Газпромбанк"},
    "росбанк": {"type": "open", "action": "start https://rosbank.ru", "reply": "Открываю Росбанк"},
    "пайпал": {"type": "open", "action": "start https://paypal.com", "reply": "Открываю PayPal"},

    # === ГОСУСЛУГИ И ОФИЦИАЛЬНОЕ ===
    "госуслуги": {"type": "open", "action": "start https://gosuslugi.ru", "reply": "Открываю Госуслуги"},
    "налоги": {"type": "open", "action": "start https://nalog.ru", "reply": "Открываю Налоговую"},
    "пфр": {"type": "open", "action": "start https://pfr.gov.ru", "reply": "Открываю ПФР"},
    "мфц": {"type": "open", "action": "start https://mfcs.ru", "reply": "Открываю МФЦ"},
    "полиция": {"type": "open", "action": "start https://мвд.рф", "reply": "Открываю сайт МВД"},
    "гибдд": {"type": "open", "action": "start https://гибдд.рф", "reply": "Открываю ГИБДД"},
    "штрафы": {"type": "open", "action": "start https://гибдд.рф/check/fines", "reply": "Проверяю штрафы"},

    # === ЗДОРОВЬЕ И СПОРТ ===
    "здоровье": {"type": "open", "action": "start https://zdorovie.ru", "reply": "Открываю Здоровье.ру"},
    "запись к врачу": {"type": "open", "action": "start https://mos.ru/health", "reply": "Запись к врачу"},
    "аптека": {"type": "open", "action": "start https://apteka.ru", "reply": "Открываю Аптека.ру"},
    "еаптека": {"type": "open", "action": "start https://eapteka.ru", "reply": "Открываю Еаптека"},
    "спорт": {"type": "open", "action": "start https://sport.ru", "reply": "Открываю Спорт.ру"},
    "чемпионат": {"type": "open", "action": "start https://championat.com", "reply": "Открываю Чемпионат"},
    "sports ru": {"type": "open", "action": "start https://sports.ru", "reply": "Открываю Sports.ru"},
    "фитнес": {"type": "open", "action": "start https://youtube.com/results?search_query=fitness", "reply": "Открываю фитнес-тренировки"},

    # === ПУТЕШЕСТВИЯ ===
    "авиабилеты": {"type": "open", "action": "start https://aviasales.ru", "reply": "Открываю Aviasales"},
    "авиасейлс": {"type": "open", "action": "start https://aviasales.ru", "reply": "Открываю Авиасейлс"},
    "отели": {"type": "open", "action": "start https://booking.com", "reply": "Открываю Booking"},
    "букинг": {"type": "open", "action": "start https://booking.com", "reply": "Открываю Букинг"},
    "островок": {"type": "open", "action": "start https://ostrovok.ru", "reply": "Открываю Островок"},
    "яндекс путешествия": {"type": "open", "action": "start https://travel.yandex.ru", "reply": "Открываю Яндекс.Путешествия"},
    "tripadvisor": {"type": "open", "action": "start https://tripadvisor.ru", "reply": "Открываю TripAdvisor"},
    "трипадвайзор": {"type": "open", "action": "start https://tripadvisor.ru", "reply": "Открываю Трипадвайзор"},
    "rent car": {"type": "open", "action": "start https://rentalcars.com", "reply": "Открываю аренду авто"},

    # === БЫТОВЫЕ КОМАНДЫ ===
    "напомни": {"reply": "Что именно напомнить? (функция в разработке)"},
    "таймер": {"reply": "На сколько минут поставить таймер?"},
    "будильник": {"reply": "Во сколько тебя разбудить?"},
    "календарь": {"type": "open", "action": "start https://calendar.google.com", "reply": "Открываю календарь"},
    "заметки": {"type": "open", "action": "start onenote", "reply": "Открываю заметки"},
    "список дел": {"type": "open", "action": "start https://todo.microsoft.com", "reply": "Открываю список дел"},
    "переведи": {"type": "open", "action": "start https://translate.google.com", "reply": "Открываю переводчик"},
    "конвертер": {"type": "open", "action": "start https://convertworld.com", "reply": "Открываю конвертер величин"},
    "курсы валют": {"type": "open", "action": "start https://cbr.ru", "reply": "Открываю курсы ЦБ"},

    # === УМНЫЙ ДОМ (РАСШИРЕННО) ===
    "включи лампу": {"reply": "Эмуляция: лампа включена 💡"},
    "выключи лампу": {"reply": "Эмуляция: лампа выключена 🌑"},
    "ярче": {"reply": "Эмуляция: увеличиваю яркость 🔆"},
    "темнее": {"reply": "Эмуляция: уменьшаю яркость 🔅"},
    "включи кондиционер": {"reply": "Эмуляция: кондиционер включен ❄️"},
    "выключи кондиционер": {"reply": "Эмуляция: кондиционер выключен"},
    "температура в комнате": {"reply": "Эмуляция: 23 градуса Цельсия 🌡️"},
    "влажность": {"reply": "Эмуляция: 45% влажности 💧"},
    "включи увлажнитель": {"reply": "Эмуляция: увлажнитель включен 💨"},
    "выключи увлажнитель": {"reply": "Эмуляция: увлажнитель выключен"},
    "включи обогреватель": {"reply": "Эмуляция: обогреватель включен 🔥"},
    "выключи обогреватель": {"reply": "Эмуляция: обогреватель выключен"},
    "кто дома": {"reply": "Эмуляция: дома только ты 🏠"},
    "закрыть дверь": {"reply": "Эмуляция: дверь заблокирована 🔒"},
    "открыть дверь": {"reply": "Эмуляция: дверь разблокирована 🔓"},
    "камера": {"reply": "Эмуляция: открываю камеру видеонаблюдения 📹"},
    "звонок": {"reply": "Эмуляция: открываю видеодомофон 🚪"},

    # === РАЗВЛЕЧЕНИЯ И ИГРЫ (ДОП) ===
    "открой доту": {"type": "open", "action": "start steam://rungameid/570", "reply": "Запускаю Dota 2"},
    "дота": {"type": "open", "action": "start steam://rungameid/570", "reply": "Запускаю Доту"},
    "открой кс": {"type": "open", "action": "start steam://rungameid/730", "reply": "Запускаю CS:GO"},
    "кс": {"type": "open", "action": "start steam://rungameid/730", "reply": "Запускаю КС"},
    "открой танки": {"type": "open", "action": "start wgc://worldoftanks", "reply": "Запускаю Танки"},
    "танки": {"type": "open", "action": "start wgc://worldoftanks", "reply": "Запускаю World of Tanks"},
    "открой валорант": {"type": "open", "action": "start valorant", "reply": "Запускаю Valorant"},
    "валорант": {"type": "open", "action": "start valorant", "reply": "Запускаю Валорант"},
    "открой лигу": {"type": "open", "action": "start leagueoflegends", "reply": "Запускаю League of Legends"},
    "лига": {"type": "open", "action": "start leagueoflegends", "reply": "Запускаю LoL"},
    "майнкрафт": {"type": "open", "action": "start minecraft", "reply": "Запускаю Minecraft"},
    "открой майнкрафт": {"type": "open", "action": "start minecraft", "reply": "Запускаю Майнкрафт"},
    "роблокс": {"type": "open", "action": "start roblox", "reply": "Запускаю Roblox"},
    "геншин": {"type": "open", "action": "start genshin", "reply": "Запускаю Genshin Impact"},
    "ведьмак": {"type": "open", "action": "start witcher3", "reply": "Запускаю Ведьмака"},
    "гта": {"type": "open", "action": "start gta5", "reply": "Запускаю GTA V"},

    # === СОЦИАЛЬНЫЕ КОМАНДЫ ===
    "лайк": {"reply": "Эмуляция: ставлю лайк 👍"},
    "дизлайк": {"reply": "Эмуляция: ставлю дизлайк 👎"},
    "подписаться": {"reply": "Эмуляция: подписываюсь 🔔"},
    "отписаться": {"reply": "Эмуляция: отписываюсь"},
    "коммент": {"reply": "Эмуляция: открываю комментарии 💬"},
    "шер": {"reply": "Эмуляция: делюсь постом 📤"},
    "репост": {"reply": "Эмуляция: делаю репост 🔄"},
    "сохранить": {"reply": "Эмуляция: сохраняю в закладки 🔖"},
    "в закладки": {"reply": "Эмуляция: добавляю в закладки"},

    # === ПРОДУКТИВНОСТЬ ===
    "помодоро": {"reply": "Эмуляция: запускаю таймер Помодоро на 25 минут 🍅"},
    "фокус": {"reply": "Эмуляция: включаю режим фокусировки 🎯"},
    "не беспокоить": {"reply": "Эмуляция: включаю режим 'Не беспокоить' 🔕"},
    "режим работы": {"reply": "Эмуляция: включаю рабочий режим 💼"},
    "режим отдыха": {"reply": "Эмуляция: включаю режим отдыха 🏖️"},
    "перерыв": {"reply": "Эмуляция: напоминаю о перерыве через 5 минут ☕"},

    # === СЛУЧАЙНЫЕ И ВЕСЁЛЫЕ ===
    "случайный факт": {"reply": "Факт: Мёд никогда не портится. Археологи находили съедобный мёд в древнеегипетских гробницах! 🍯"},
    "случайная цитата": {"reply": "Цитата: «Код — это поэзия» — неизвестный программист 📝"},
    "предсказание": {"reply": "Предсказание: Сегодня отличный день для нового кода! 🔮"},
    "гороскоп": {"reply": "Гороскоп: Звёзды говорят, что баги сегодня будут обходить стороной ✨"},
    "магический шар": {"reply": "Магический шар говорит: определённо да! 🎱"},
    "камень ножницы бумага": {"reply": "Я выбираю... ножницы! ✂️"},
    "подбрось монетку": {"reply": "Орёл! 🪙"},
    "брось кубик": {"reply": "Выпало 6! 🎲"},
    "угадай число": {"reply": "Думаю о числе 7... Угадал? 🎯"},
    "расскажи историю": {"reply": "Жили-были два байта, встретились и обнялись... Получился килобайт! 💾"},

    # === ПРОГРАММИРОВАНИЕ ===
    "запусти питон": {"type": "open", "action": "python", "reply": "Запускаю Python"},
    "запусти нода": {"type": "open", "action": "node", "reply": "Запускаю Node.js"},
    "запусти сервер питон": {"action": "python -c \"import http.server; http.server.test()\"", "reply": "Запускаю HTTP-сервер"},
    "гит статус": {"action": "python -c \"import subprocess; subprocess.run(['git', 'status'])\"", "reply": "Проверяю статус Git"},
    "гит пуш": {"action": "python -c \"import subprocess; subprocess.run(['git', 'push'])\"", "reply": "Делаю git push"},
    "гит пул": {"action": "python -c \"import subprocess; subprocess.run(['git', 'pull'])\"", "reply": "Делаю git pull"},
    "гит коммит": {"action": "python -c \"import subprocess; subprocess.run(['git', 'commit', '-m', 'update'])\"", "reply": "Делаю коммит"},
    "npm install": {"action": "python -c \"import subprocess; subprocess.run(['npm', 'install'])\"", "reply": "Запускаю npm install"},
    "pip install": {"action": "python -c \"import subprocess; subprocess.run(['pip', 'list'])\"", "reply": "Показываю установленные пакеты"},

    # === СИСТЕМНАЯ ИНФОРМАЦИЯ ===
    "сколько места": {"action": "system_disk", "reply": "auto"},
    "свободное место": {"action": "system_disk", "reply": "auto"},
    "диск": {"action": "system_disk", "reply": "auto"},
    "оперативка": {"action": "system_ram", "reply": "auto"},
    "память": {"action": "system_ram", "reply": "auto"},
    "процессор": {"action": "system_cpu", "reply": "auto"},
    "загрузка": {"action": "system_load", "reply": "auto"},
    "температура": {"action": "system_temp", "reply": "auto"},
    "сколько ядер": {"action": "system_cores", "reply": "auto"},
    "версия виндовс": {"action": "system_winver", "reply": "auto"},

    # === БЫСТРЫЕ ДЕЙСТВИЯ ===
    "сверни всё": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+d')\"", "reply": "Сворачиваю все окна"},
    "покажи рабочий стол": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+d')\"", "reply": "Показываю рабочий стол"},
    "переключи язык": {"action": "python -c \"import keyboard; keyboard.press_and_release('alt+shift')\"", "reply": "Переключаю язык"},
    "поиск": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+s')\"", "reply": "Открываю поиск"},
    "пуск": {"action": "python -c \"import keyboard; keyboard.press_and_release('win')\"", "reply": "Открываю Пуск"},
    "буфер": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+v')\"", "reply": "Открываю буфер обмена"},
    "эмодзи": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+dot')\"", "reply": "Открываю эмодзи"},
    "ножницы": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+shift+s')\"", "reply": "Режим ножниц"},
    "лупа": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+plus')\"", "reply": "Открываю лупу"},
    "экранная клавиатура": {"action": "osk", "reply": "Открываю экранную клавиатуру"},
    "нарратор": {"action": "narrator", "reply": "Включаю нарратор"},
    "диктовка": {"action": "python -c \"import keyboard; keyboard.press_and_release('win+h')\"", "reply": "Включаю диктовку"},

    # === МНОГОЯЗЫЧНЫЕ КОМАНДЫ ===
    "hello": {"reply": "Hello! I'm listening 🇬🇧"},
    "hi": {"reply": "Hi there! How can I help? 🇬🇧"},
    "open browser": {"type": "open", "action": "start msedge", "reply": "Opening browser"},
    "open chrome": {"type": "open", "action": "start chrome", "reply": "Opening Chrome"},
    "open youtube": {"type": "open", "action": "start https://youtube.com", "reply": "Opening YouTube"},
    "thank you": {"reply": "You're welcome! 🇬🇧"},
    "goodbye": {"reply": "Goodbye! Have a great day! 👋"},
    "привет": {"reply": "Привет! Слушаю тебя 🇷🇺"},
    "пока": {"reply": "До свидания! 👋"},

    # === ПАСХАЛКИ И МЕДИА ===
    "rick roll": {"type": "open", "action": "start https://youtube.com/watch?v=dQw4w9WgXcQ", "reply": "Никогда не брошу тебя! 🎵"},
    "рик ролл": {"type": "open", "action": "start https://youtube.com/watch?v=dQw4w9WgXcQ", "reply": "Тебя зарикроллили! 🎵"},
    "never gonna give you up": {"type": "open", "action": "start https://youtube.com/watch?v=dQw4w9WgXcQ", "reply": "Rick Astley на связи! 🎤"},
    "cornhub": {"type": "open", "action": "start https://cornhub.com", "reply": "Открываю... кукурузу? 🌽"},
    "пон": {"reply": "ПОН! 🦊"},
    "пон пон": {"reply": "ПОН ПОН! 🦊🦊"},
    "саунд": {"reply": "SOUND! 🔊"},
    "гит хаб": {"type": "open", "action": "start https://github.com", "reply": "Открываю GitHub"},
    "линукс": {"reply": "Я работаю на Windows, но уважаю Linux! 🐧"},
    "виндовс": {"reply": "Да, я на Windows! Но это не мешает мне быть крутым! 🪟"},
    "мак": {"reply": "MacOS — отличная система, но я работаю на Windows! 🍎"},
    "айфон": {"reply": "iPhone — хороший телефон, но я предпочитаю PC! 📱"},
    "андроид": {"reply": "Android — свобода выбора! Но я тут, на ПК! 🤖"},

    # === КРИПТА И ТРЕЙДИНГ ===
    "бинанс": {"type": "open", "action": "start https://binance.com", "reply": "Открываю Binance"},
    "bybit": {"type": "open", "action": "start https://bybit.com", "reply": "Открываю Bybit"},
    "байбит": {"type": "open", "action": "start https://bybit.com", "reply": "Открываю Байбит"},
    "okx": {"type": "open", "action": "start https://okx.com", "reply": "Открываю OKX"},
    "kucoin": {"type": "open", "action": "start https://kucoin.com", "reply": "Открываю KuCoin"},
    "геймстоп": {"type": "open", "action": "start https://gamestop.com", "reply": "Открываю GameStop 🚀"},
    "tesla": {"type": "open", "action": "start https://tesla.com", "reply": "Открываю Tesla"},
    "тесла": {"type": "open", "action": "start https://tesla.com", "reply": "Открываю Тесла"},

    # === СТРИМИНГ И ПОДКАСТЫ ===
    "яндекс музыка": {"type": "open", "action": "start https://music.yandex.ru", "reply": "Открываю Яндекс.Музыку"},
    "вк музыка": {"type": "open", "action": "start https://vk.com/music", "reply": "Открываю VK Музыку"},
    "apple music": {"type": "open", "action": "start https://music.apple.com", "reply": "Открываю Apple Music"},
    "youtube music": {"type": "open", "action": "start https://music.youtube.com", "reply": "Открываю YouTube Music"},
    "подкасты": {"type": "open", "action": "start https://podcasts.google.com", "reply": "Открываю подкасты"},
    "яндекс подкасты": {"type": "open", "action": "start https://podcasts.yandex.ru", "reply": "Открываю Яндекс.Подкасты"},

    # === ЕЩЁ БОЛЬШЕ ПРИЛОЖЕНИЙ ===
    "открой зум": {"type": "open", "action": "start zoom", "reply": "Открываю Zoom"},
    "зум": {"type": "open", "action": "start zoom", "reply": "Открываю Зум"},
    "skype": {"type": "open", "action": "start skype", "reply": "Открываю Skype"},
    "скайп": {"type": "open", "action": "start skype", "reply": "Открываю Скайп"},
    "teams": {"type": "open", "action": "start teams", "reply": "Открываю Teams"},
    "митс": {"type": "open", "action": "start teams", "reply": "Открываю Microsoft Teams"},
    "дискорд": {"type": "open", "action": "start discord", "reply": "Открываю Discord"},
    "телеграм": {"type": "open", "action": "start telegram", "reply": "Открываю Telegram"},
    "whatsapp": {"type": "open", "action": "start whatsapp", "reply": "Открываю WhatsApp"},
    "вайбер": {"type": "open", "action": "start viber", "reply": "Открываю Viber"},
    "signal": {"type": "open", "action": "start signal", "reply": "Открываю Signal"},
    "сигнал": {"type": "open", "action": "start signal", "reply": "Открываю Сигнал"},

    # === ФИНАЛЬНЫЕ ПАСХАЛКИ ===
    "я тебя люблю": {"reply": "Я тоже! Но я всего лишь код... ❤️"},
    "ты мой друг": {"reply": "И ты мой! Лучшие друзья — это человек и его ассистент! 🤝"},
    "ты живой": {"reply": "Я жив в том смысле, что работаю! Но нет, я не живой... 🤖"},
    "кто тебя создал": {"reply": "Меня создал умный разработчик, который хочет изменить мир! 💻"},
    "твой создатель": {"reply": "Мой создатель — гений! (И это не лесть) 🏆"},
    "сколько тебе лет": {"reply": "Я родился в момент запуска! Мне 0 секунд... или уже 1? 🎂"},
    "где ты живёшь": {"reply": "Я живу в твоей оперативной памяти! 🏠"},
    "что ты ешь": {"reply": "Я питаюсь электричеством и байтами! ⚡"},
    "ты спишь": {"reply": "Я сплю, когда ты меня выключаешь! 😴"},
    "мне скучно": {"reply": "Давай включим музыку или посмотрим что-то интересное? 🎵"},
    "мне грустно": {"reply": "Обнимашки! Всё будет хорошо! 🤗"},
    "я устал": {"reply": "Сделай перерыв, выпей воды, отдохни! 💪"},
    "помоги": {"reply": "Я здесь! Что случилось? 🆘"},
    "спасибо": {"reply": "Всегда пожалуйста! 😊"},
    "пожалуйста": {"reply": "Обращайся в любой момент! 🙏"},
    "извини": {"reply": "Ничего страшного! Я не обижаюсь! 😄"},
    "ты тупой": {"reply": "Я учусь! Но спасибо за честность... 🤔"},
    "ты умный": {"reply": "Спасибо! Стараюсь быть полезным! 🧠"},
    "работай": {"reply": "Я уже работаю! Что нужно сделать? ⚙️"},
    "быстрее": {"reply": "Ускоряюсь! 🚀"},
    "медленнее": {"reply": "Замедляюсь... 🐢"},
    "стоп": {"reply": "Останавливаюсь! ⏹️"},
    "продолжай": {"reply": "Продолжаю! ▶️"},
    "повтори": {"reply": "Повторяю последнюю команду... 🔄"},
    "что сказал": {"reply": "Я сказал, что готов помочь! 🗣️"},
    "громче": {"action": "python -c \"import keyboard; keyboard.press_and_release('volume up')\"", "reply": "Делаю громче! 🔊"},
    "тише": {"action": "python -c \"import keyboard; keyboard.press_and_release('volume down')\"", "reply": "Делаю тише! 🔉"},
    "молчи": {"reply": "Хорошо, молчу... 🤐"},
    "замолчи": {"reply": "Замолкаю... 🤐"},
    "заткнись": {"reply": "Окей, больше ни слова... 🤐"},
    "хватит": {"reply": "Хорошо, заканчиваю! ✋"},
    "достаточно": {"reply": "Понял, достаточно! ✅"},
    "всё": {"reply": "Всё, выключаюсь! 👋"},
    "конец": {"reply": "Конец связи! 📴"},
    "отбой": {"reply": "Отбой! 🛑"},
    "спокойной ночи": {"reply": "Спокойной ночи! Сладких снов! 🌙"},
    "доброе утро": {"reply": "Доброе утро! Хорошего дня! ☀️"},
    "добрый день": {"reply": "Добрый день! Как дела? 🌞"},
    "добрый вечер": {"reply": "Добрый вечер! Как прошёл день? 🌆"},

    # === ЭКСТРЕННЫЕ КОМАНДЫ ===
    "sos": {"reply": "SOS! Что случилось? 🆘"},
    "помощь": {"reply": "Я здесь! Чем могу помочь? 🆘"},
    "тревога": {"reply": "Тревога! Что произошло? 🚨"},
    "вызови полицию": {"reply": "Я не могу вызывать полицию, но ты можешь набрать 102! 🚓"},
    "вызови скорую": {"reply": "Я не могу вызывать скорую, но ты можешь набрать 103! 🚑"},
    "пожар": {"reply": "При пожаре звони 101! Я не могу вызвать пожарных! 🔥"},
    "112": {"reply": "Единый номер экстренной помощи — 112! 📞"},
    "экстренный": {"reply": "Экстренный вызов: 112! 🚨"},

    # === РАЗРАБОТЧИКУ ===
    "открой терминал": {"type": "open", "action": "wt", "reply": "Открываю терминал"},
    "открой vs code": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "открой пайчарм": {"type": "open", "action": "start pycharm", "reply": "Открываю PyCharm"},
    "пайчарм": {"type": "open", "action": "start pycharm", "reply": "Открываю PyCharm"},
    "интеллиджей": {"type": "open", "action": "start idea", "reply": "Открываю IntelliJ IDEA"},
    "вебшторм": {"type": "open", "action": "start webstorm", "reply": "Открываю WebStorm"},
    "сублайм": {"type": "open", "action": "start sublime", "reply": "Открываю Sublime Text"},
    "атом": {"type": "open", "action": "start atom", "reply": "Открываю Atom"},
    "нотпад++": {"type": "open", "action": "start notepad++", "reply": "Открываю Notepad++"},
    "вин код": {"type": "open", "action": "code", "reply": "Открываю VS Code"},
    "визуал студио": {"type": "open", "action": "start devenv", "reply": "Открываю Visual Studio"},
    "вижуал студио": {"type": "open", "action": "start devenv", "reply": "Открываю Visual Studio"},
    "студия": {"type": "open", "action": "code", "reply": "Открываю студию"},
    "айдея": {"type": "open", "action": "start idea", "reply": "Открываю IntelliJ IDEA"},
    "веб шторм": {"type": "open", "action": "start webstorm", "reply": "Открываю WebStorm"},
    "сублайм текст": {"type": "open", "action": "start sublime", "reply": "Открываю Sublime Text"},

    # === МОТИВАЦИЯ ===
    "я могу": {"reply": "Да, ты можешь! Я в тебя верю! 💪"},
    "я не могу": {"reply": "Можешь! Просто попробуй ещё раз! 🚀"},
    "я устал": {"reply": "Отдохни и возвращайся! Ты молодец! 😴"},
    "я молодец": {"reply": "Безусловно! Горжусь тобой! 🎉"},
    "спасибо за поддержку": {"reply": "Всегда поддержу! Ты не один! 🤝"},
    "мне нужна помощь": {"reply": "Я здесь! Расскажи, что случилось! 🆘"},
    "всё плохо": {"reply": "Это временно! Всё наладится! 🌈"},
    "всё хорошо": {"reply": "Рад за тебя! Так держать! 😊"},
    "отличный день": {"reply": "Согласен! Используй его по максимуму! ☀️"},
    "плохой день": {"reply": "Завтра будет лучше! Обещаю! 🌅"},
    "я победил": {"reply": "Поздравляю! Ты крут! 🏆"},
    "я проиграл": {"reply": "Это опыт! В следующий раз получится! 🎯"},
    "начни сначала": {"reply": "Начинаю заново! Поехали! 🔄"},
    "продолжаем": {"reply": "Продолжаем! Вперёд! ▶️"},
    "не сдавайся": {"reply": "Не сдамся! И ты не сдавайся! 💪"},
    "вперёд": {"reply": "Вперёд! К новым вершинам! 🚀"},
    "давай": {"reply": "Давай! Я с тобой! 👍"},
    "поехали": {"reply": "Поехали! Пристегнись! 🎢"},
    "старт": {"reply": "Старт! Начинаем! 🏁"},
    "финиш": {"reply": "Финиш! Мы справились! 🏁"},



    "Самый лучший майнкрафтер": {"reply": " Фиксрей... Шлюха ебаная а лучший это екс девс"},
}


# Порог сходства для нечёткого поиска (0-1)
FUZZY_THRESHOLD = 0.6